<?php

namespace ElementsHiveForBreakdancePro\Constants;

define('EH_EASING_TYPES', [
    "linear",
    "expo.in",
    "expo.out",
    "expo.inOut",
    "power1.in",
    "power1.out",
    "power1.inOut",
    "power2.in",
    "power2.out",
    "power2.inOut",
    "power3.in",
    "power3.out",
    "power3.inOut",
    "power4.in",
    "power4.out",
    "power4.inOut",
    "sine.in",
    "sine.out",
    "sine.inOut",
    "circ.in",
    "circ.out",
    "circ.inOut",
    "back.in",
    "back.out",
    "back.inOut",
    "elastic.in",
    "elastic.out",
    "elastic.inOut",
    "bounce.in",
    "bounce.out",
    "bounce.inOut",
]);
